---
- name: 'Download Bitcoin Core {{bitcoin_core_version}} binaries'
  get_url:
    url: 'https://bitcoincore.org/bin/bitcoin-core-{{bitcoin_core_version}}/{{bitcoin_core_file}}'
    dest: '{{download_destination}}'
    checksum: '{{bitcoin_core_sha256}}'
    mode: 0750
  tags:
    - always

- name: 'Create {{bitcoin_path}} directory'
  become: yes
  file:
    path: '{{bitcoin_path}}'
    state: directory
    owner: pi
    group: pi
    mode: 0750

- name: 'Create {{bitcoin_config_path}} directory'
  file:
    path: '{{bitcoin_config_path}}'
    state: directory
    owner: pi
    group: pi
    mode: 0750

- name: 'Unarchive {{bitcoin_core_file}} file'
  unarchive:
    src: '{{download_destination}}/{{bitcoin_core_file}}'
    dest: '/opt/bitcoin'
    extra_opts: [--strip-components=1]
    owner: pi
    group: pi
    mode: 750
    remote_src: yes

- name: 'Add Bitcoin core binaries directory to PATH in pi .profile file'
  lineinfile:
    path: /home/pi/.profile
    line: 'export PATH=$PATH:/opt/bitcoin/bin'
    create: yes
